name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  test:
    name: build and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3cmd sync
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: 'github-actions-tests'
          AWS_REGION: 'us-east-1'
          S3CMD_SOURCE_DIR: '__tests__'
          S3CMD_EXCLUDE: '.git/*'
          S3CMD_EXCLUDE_FROM: ''
          S3CMD_DELETE_REMOVED: 'false'
          S3CMD_ADD_HEADERS: "Expires:$(date -u +'%a, %d %b %Y %H:%M:%S GMT')|Cache-Control: max-age=31556952"
          S3CMD_CF_INVALIDATE: 'false'
          S3CMD_EXTRA_OPTS: '--verbose --storage-class=STANDARD_IA'
      - uses: actions/checkout@v2
      - name: S3cmd sync without exclude some parameters
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: 'github-actions-tests'
          AWS_REGION: 'us-east-1'
          S3CMD_SOURCE_DIR: '__tests__'
          S3CMD_EXCLUDE: ''
          S3CMD_EXCLUDE_FROM: ''
          S3CMD_DELETE_REMOVED: 'false'
          S3CMD_ADD_HEADERS: ''
          S3CMD_CF_INVALIDATE: 'false'
          S3CMD_EXTRA_OPTS: '--verbose --storage-class=STANDARD_IA'
